---
    name: Build

    on: [push, pull_request]

    jobs:
      pre-commit:
        name: Pre-commit (linting)
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
          - name: Checkout Code
            uses: actions/checkout@v3

          - name: Run pre-commit
            uses: pre-commit/action@v3.0.0

      pytest-in-venv:
        name: Python tests
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
          - name: Checkout Code
            uses: actions/checkout@v3

          - name: Setup Python
            uses: actions/setup-python@v4
            with:
              python-version: "3.11"
              cache: pip

          - name: Install dependencies
            run: pip install -r requirements/requirements-test.txt

          - name: Run the tests
            run: pytest