---
# To trigger a package release, create a new tag in the format v.x.x.x with semantic versioning
name: PyPi Package Release

on:
  push:
    tags:
      # Only run this workflow for tags that start with 'v.' (release tags)
      - 'v*'

jobs:
  pypi_release:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: pip

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
        pip install wheel twine

    - name: Build the package
      run: |
        python setup.py sdist bdist_wheel

    - name: Smoke Test
      run: |
        pip install dist/*.whl
        aicodebot -V

    - name: Publish to PyPi
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine check dist/*
        twine upload dist/*

    - name: Create Github Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false