name: PyPi Package Release

on:
  push:
    tags:
      - 'v*'

jobs:
  pypi_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
    - name: Build
      run: |
        pip install wheel
        python setup.py sdist bdist_wheel
    - name: Smoke Test
      run: |
        pip install dist/*.whl
        aicodebot version
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pip install twine
        twine check dist/*
        twine upload dist/*
